[package]
name = "fsr2-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.3.1"
widestring = "1.0.2"

[build-dependencies]
anyhow = "1.0.70"
fs_extra = "1.3.0"

[features]
vk = []
dx12 = []